baseURL = "https://kanazawanaoaki.github.io"
title = "Naoaki Kanazawa"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[markup.highlight]
noClasses = false
# style = "github-dark"

[params]
faviconSVG = "images/my-favicon.svg"
favicon_16 = "images/my-favicon-16.ico"
favicon_32 = "images/my-favicon-32.ico"
author = "Naoaki Kanazawa"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Naoaki Kanazawa's personal website"
keywords = "blog,developer,personal"
info = ["Ph.D. Student at JSK Robotics Laboratory", "The University of Tokyo"]
avatarURL = "images/my_photo.jpeg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2023
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
# outboundLinksTracking = true
# fileDownloadsTracking = true

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
[params.googleTagManager]
id = "G-P3RNNXY2FH"

# If you want to use Yandex Metrika(https://metrika.yandex.ru) for analytics, add this section
# [params.yandexMetrika]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to use microanalytics.io for analytics, add this section
# [params.microAnalytics]
# id = "ABCDE"
# dnt = "false" # respect DNT tracker, "true" by default

# If you want to use Pirsch(https://pirsch.io) for analytics, add this section
# [params.pirsch]
# code = "ABCDE"

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/Kanazawanaoaki/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 2
url = "https://twitter.com/Naoaki_Kanazawa"

[[params.social]]
name = "Google Scholar"
icon = "fa fa-2x fa-graduation-cap"
weight = 3
url = "https://scholar.google.co.jp/citations?user=WCjv9PcAAAAJ"

# [[params.social]]
# name = "LinkedIn"
# icon = "fa fa-2x fa-linkedin"
# weight = 3
# url = "https://www.linkedin.com/in/johndoe/"

# [[params.social]]
# name = "Medium"
# icon = "fa fa-2x fa-medium"
# weight = 5
# url = "https://medium.com/@johndoe"

# [[params.social]]
# name = "RSS"
# icon = "fa fa-2x fa-rss"
# weight = 6
# url = "https://myhugosite.com/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

[languages.en]
# languageName = ":uk:"
languageName = "English"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Publications"
weight = 2
url = "publications/"

[[languages.en.menu.main]]
name = "Posts"
weight = 3
url = "posts/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[languages.ja]
# languageName = ":japan:"
languageName = "日本語"
title = "金沢 直晃"

[languages.ja.params]
author = "金沢 直晃"
info = ["東京大学大学院 知能機械情報学専攻","情報システム工学研究室 博士課程"]
avatarURL = "images/my_photo.jpeg"
# description = "Sítio pessoal de João Ninguém"
keywords = "blog,desenvolvedor,pessoal"

[[languages.ja.menu.main]]
name = "自己紹介"
weight = 1
url = "about/"

[[languages.ja.menu.main]]
name = "成果"
weight = 2
url = "publications/"

[[languages.ja.menu.main]]
name = "投稿"
weight = 3
url = "posts/"

[[languages.ja.menu.main]]
name = "連絡先"
weight = 5
url = "contact/"
